CREATE TABLE answer
(
  order_id INTEGER PRIMARY KEY,
  item VARCHAR (255) PRIMARY KEY,
  amount INTEGER PRIMARY KEY,
  first_name VARCHAR(255) PRIMARY KEY,
  last_name VARCHAR(255) PRIMARY KEY,
  age INTEGER PRIMARY KEY,
  country VARCHAR(255) PRIMARY KEY
);